language: go

sudo: false

go:
  - release
  - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

install:
    - go get -t simonwaldherr.de/go/GolangSortingVisualization
    - go get -t github.com/SimonWaldherr/GolangSortingVisualization

script:
    - go test -v -coverprofile=gsv.coverprofile
    - $HOME/gopath/bin/goveralls -coverprofile=gsv.coverprofile -service=travis-ci -repotoken=MSToT9De9SIxTAH8BD3JsN68xfWAPEqDP

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always